EC2 inventory plugin pulled from ansible source.
Add `boto` to requirements because it's required by this script:

    (ansible)➜  tsuru-ansible git:(dynamic_inventory) ✗ ansible-playbook -i ec2.py --vault-password-file vault_password.sh site-aws.yml -e "deploy_env=dcarley" -e "domain_name=tsuru.paas.alphagov.co.uk" -e "ip_field=ec2_private_ip_address"
    Fetching vault password from account 'tsuru-ansible-vault' in keychain..
    ERROR: Inventory script (ec2.py) had an execution error: Traceback (most recent call last):
      File "/Users/dcarley/projects/paas/tsuru-ansible/ec2.py", line 121, in <module>
        import boto
    ImportError: No module named boto